# 파일 불러오기
- csv 파일, 엑셀 파일
- output/ 폴더에 있는 result.csv 파일 불러오기
- Gemini 도움 받아서 엑셀 파일 불러오기 하세요.

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [7]:
import pandas as pd

DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/2026/이어드림스쿨6기/4주차/02_pandas와데이터시각화/output/'

r_csv = pd.read_csv(DATA_PATH + 'result.csv')

r_excel = pd.read_excel(DATA_PATH + 'result.xlsx', sheet_name = 'tips')

In [6]:
r_csv.head()
# r_csv.info()

   total_bill   tip     sex smoker  day    time  size
0       21.01  3.50    Male     No  Sun  Dinner     3
1       24.59  3.61  Female     No  Sun  Dinner     4
2       25.29  4.71    Male     No  Sun  Dinner     4
3       26.88  3.12    Male     No  Sun  Dinner     4
4       35.26  5.00  Female     No  Sun  Dinner     4

In [8]:
r_excel.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       21.01  3.50    Male     No  Sun  Dinner     3
1           1       24.59  3.61  Female     No  Sun  Dinner     4
2           2       25.29  4.71    Male     No  Sun  Dinner     4
3           3       26.88  3.12    Male     No  Sun  Dinner     4
4           4       35.26  5.00  Female     No  Sun  Dinner     4